# Generated by Django 5.2.7 on 2025-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('BACT', 'Bacteriólogo/a'), ('MICR', 'Microbiólogo/a'), ('BIOL', 'Biólogo/a')], max_length=4)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
